### Title: <span style='color:red;'>US_GUN_VIOLENCE</span>

### Introduction:
##### Project Description
Human societies are plagued with several social issues that can be life-threatening at times. A notable case is the issue of gun violence in the United States which results in tens of thousands of deaths and injuries annually. In this project we perform a deep exploration of gun violence incidents reported in the US.

##### Dataset Description:
The dataset used in this project was obtained from [source](https://www.kaggle.com/jameslko/gun-violence-data)
##### Overall Goal:
<span style='color:red;'>My goal is to explore this data to draw useful insights from data about the gun violence in the US.</span>

##### Specific goals
At the end of this exploratory analysis, I hope to answer the following questions:
1. how much has has gun violence increased over the years?
2. how much has deaths per year due to gun violence changed over the years?
3. where in the US is gun violence most prevalent





### Load Modules and Data

For the purpose of analysis, I would be making use of the following modules. Next, I would load in my data.

In [1]:
#imports
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


In [37]:
import os
os.chdir("F:/micro masters/PYTHON/US Gun Violence")

In [38]:
# load data
guns = pd.read_csv("guns.csv")


### Preview of Data

In [12]:
guns.head(5)

incident_id      date           state city_or_county  n_killed  n_injured  \
0       461105  1/1/2013    Pennsylvania     Mckeesport         0          4   
1       460726  1/1/2013      California      Hawthorne         1          3   
2       478855  1/1/2013            Ohio         Lorain         1          3   
3       478925  1/5/2013        Colorado         Aurora         4          0   
4       478959  1/7/2013  North Carolina     Greensboro         2          2   

                                        incident_url  \
0  http://www.gunviolencearchive.org/incident/461105   
1  http://www.gunviolencearchive.org/incident/460726   
2  http://www.gunviolencearchive.org/incident/478855   
3  http://www.gunviolencearchive.org/incident/478925   
4  http://www.gunviolencearchive.org/incident/478959   

                                          source_url  \
0  http://www.post-gazette.com/local/south/2013/0...   
1  http://www.dailybulletin.com/article/zz/201301...   
2  http://chronicle.northcoastnow.com/2013/02/14/...   
3  http://www.dailydemocrat.com/20130106/aurora-s...   
4  http://www.journalnow.com/news/local/article_d...   

   incident_url_fields_missing  congressional_district  ... longitude  \
0                        False                    14.0  ...  -79.8559   
1                        False                    43.0  ... -118.3330   
2                        False                     9.0  ...  -82.1377   
3                        False                     6.0  ... -104.8020   
4                        False                     6.0  ...  -79.9569   

  n_guns_involved                                              notes  \
0             NaN  Julian Sims under investigation: Four Shot and...   
1             NaN  Four Shot; One Killed; Unidentified shooter in...   
2             2.0                                                NaN   
3             NaN                                                NaN   
4             2.0  Two firearms recovered. (Attempted) murder sui...   

                     participant_age  \
0                              0::20   
1                              0::20   
2  0::25||1::31||2::33||3::34||4::33   
3         0::29||1::33||2::56||3::33   
4         0::18||1::46||2::14||3::47   

                               participant_age_group  \
0  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
1  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
2  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
3  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
4  0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...   

                            participant_gender participant_relationship  \
0         0::Male||1::Male||3::Male||4::Female                      NaN   
1                                      0::Male                      NaN   
2  0::Male||1::Male||2::Male||3::Male||4::Male                      NaN   
3         0::Female||1::Male||2::Male||3::Male                      NaN   
4       0::Female||1::Male||2::Male||3::Female                3::Family   

                                  participant_status  \
0  0::Arrested||1::Injured||2::Injured||3::Injure...   
1      0::Killed||1::Injured||2::Injured||3::Injured   
2  0::Injured, Unharmed, Arrested||1::Unharmed, A...   
3         0::Killed||1::Killed||2::Killed||3::Killed   
4       0::Injured||1::Injured||2::Killed||3::Killed   

                                    participant_type  \
0  0::Victim||1::Victim||2::Victim||3::Victim||4:...   
1  0::Victim||1::Victim||2::Victim||3::Victim||4:...   
2  0::Subject-Suspect||1::Subject-Suspect||2::Vic...   
3  0::Victim||1::Victim||2::Victim||3::Subject-Su...   
4  0::Victim||1::Victim||2::Victim||3::Subject-Su...   

                                             sources  
0  http://pittsburgh.cbslocal.com/2013/01/01/4-pe...  
1  http://losangeles.cbslocal.com/2013/01/01/man-...  
2  http://www.morningjournal.com/general-news/201...  
3  http://denver.cbslocal.com/2013/01/06/officer-... 

In [5]:
guns.shape

(239677, 24)

### 1. Data quality Assessment
**Goal**:
To perform an initial assessment of the data quality that would allow me to go to the next steps of my analysis.

First, I will take out of the initial data, the relevant subset that interests my exploration of the data.

Secondly, to complete this step, I would be examining the dataset for the following data quality issues:
- Accuracy of field values
- Missing values
- Duplicate entries

#### IDENTIFYING RELEVANT COLUMNS

To simplify the data, the first thing I want to do is to have a look at the variable names to see which ones contain the data needed for any kind of intuitive analysis that I am interested in.

In [13]:
guns.columns

Index(['incident_id', 'date', 'state', 'city_or_county', 'n_killed',
       'n_injured', 'incident_url', 'source_url',
       'incident_url_fields_missing', 'congressional_district', 'gun_stolen',
       'gun_type', 'latitude', 'location_description', 'longitude',
       'n_guns_involved', 'notes', 'participant_age', 'participant_age_group',
       'participant_gender', 'participant_relationship', 'participant_status',
       'participant_type', 'sources'],
      dtype='object')

**comment:** Looking at the variable names, I will be removing the following columns: ('incident_id', 'incident_url', 'source_url',  'incident_url_fields_missing', 'congressional_district', 'gun_stolen','gun_type','n_guns_involved', 'notes', 'sources', 'location_description', 'participant_status', 'participant_type','participant_gender', 'participant_relationship',)

In [39]:
new_guns=guns[['date', 'state', 'city_or_county', 'n_killed','n_injured', 'latitude', 'longitude', 'participant_age', 'participant_age_group']]
new_guns.shape

(239677, 9)

#### PROFILING THE DATA

From above, I have 9 variables and 239677 observations from the dataset that are of interest to me.

The first step towards any data analysis is to have an overview of the data. To help me achieve this goal, I would be using the pandas profiling method.

In [7]:
import pandas_profiling as pp

In [8]:
profile=pp.ProfileReport(new_guns)
profile

In [9]:
new_guns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 9 columns):
date                     239677 non-null object
state                    239677 non-null object
city_or_county           239677 non-null object
n_killed                 239677 non-null int64
n_injured                239677 non-null int64
latitude                 231754 non-null float64
longitude                231754 non-null float64
participant_age          147379 non-null object
participant_age_group    197558 non-null object
dtypes: float64(2), int64(2), object(5)
memory usage: 16.5+ MB


**ASSESSMENT OF FEILD VALUES**

In [10]:
import numpy as np
new_guns.describe(include=np.float64)

latitude      longitude
count  231754.000000  231754.000000
mean       37.546598     -89.338348
std         5.130763      14.359546
min        19.111400    -171.429000
25%        33.903400     -94.158725
50%        38.570600     -86.249600
75%        41.437375     -80.048625
max        71.336800      97.433100

In [40]:
new_guns['date']=pd.to_datetime(new_guns['date'])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [36]:

for column in new_guns:
    Categories=[]
    new_guns[column]=pd.Categorical(new_guns[column])
    Categories.append([column, new_guns[column].cat.categories])
    
    print('\n')
    print(Categories)
    print(' ')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.




[['date', DatetimeIndex(['2013-01-01', '2013-01-05', '2013-01-07', '2013-01-19',
               '2013-01-21', '2013-01-23', '2013-01-25', '2013-01-26',
               '2013-02-02', '2013-02-03',
               ...
               '2018-03-22', '2018-03-23', '2018-03-24', '2018-03-25',
               '2018-03-26', '2018-03-27', '2018-03-28', '2018-03-29',
               '2018-03-30', '2018-03-31'],
              dtype='datetime64[ns]', length=1725, freq=None)]]
 


[['state', Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon'

#### ANALYZING THE OVERVIEW OF THE DATA

SHAPE

From the above output, the 9 variables of my data comprises of 4 numerical variables and 5 categorical variables.

MISSING VALUE

I have 7% of missing data. participant_age has a total of 38.5% of its inputs missen and that is the highest. For this reason and the fact that participant_age_group is a better variable to capture age, I would be removing this variables. This is because, with such high number of missing values, any analysis done with these variable can be highly misleading with high errors.

After this, I would further remove any additional rows with missing values.

FIELD VALUES

The participant_age variable appears to have some unreasonable values. For instance:['0.041666667', '0.042361111', '0.043055556', '0.04375', '0.044444444', '0.045138889', '0.045833333', '0.046527778', '0.047916667','0.048611111'] I would need to remove such inputs should they still exist after dealing with missing values and duplicates.

To help me deal with these issues for the remaining variables in the object format, I would need to convert their categories to sub-categories to fish out these unreasonable inputs and also facilitate my analysis.

DUPLICATES

The data currently has 864 duplicate rows. After dealing with the missing values, this may reduce the remaining duplicates and then, i would remove these duplicates.


### 2. Data Cleaning
Given, the issues I have raised above, I will be doing the relevant data cleaning needed to help smoothen my subsequent analysis.
First, I will deal with missing values.
Next, unreasonable column values
Lastly, duplicates.
Also, I may subset certain coulmns where necessary.

DEALING WITH MISSING VALUES

In [24]:
new_guns=new_guns.drop(['participant_age'], axis=1)

In [25]:
new_guns=new_guns.dropna()

In [26]:
new_guns.shape

(190571, 8)

DEALING WITH DUPLICATES

In [27]:
new_guns.drop_duplicates

<bound method DataFrame.drop_duplicates of              date                 state            city_or_county  n_killed  \
0      2013-01-01          Pennsylvania                Mckeesport         0   
1      2013-01-01            California                 Hawthorne         1   
2      2013-01-01                  Ohio                    Lorain         1   
3      2013-01-05              Colorado                    Aurora         4   
4      2013-01-07        North Carolina                Greensboro         2   
5      2013-01-07              Oklahoma                     Tulsa         4   
6      2013-01-19            New Mexico               Albuquerque         5   
8      2013-01-21            California                 Brentwood         0   
9      2013-01-23              Maryland                 Baltimore         1   
10     2013-01-23             Tennessee               Chattanooga         1   
11     2013-01-25              Missouri               Saint Louis         1   
12     20

In [28]:
new_guns.shape

(190571, 8)

From above output, it is clear that the duplicates no longer exist after the initial cleaning.

**Let's have an overview of new data**

In [29]:
new_guns.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 190571 entries, 0 to 239676
Data columns (total 8 columns):
date                     190571 non-null datetime64[ns]
state                    190571 non-null object
city_or_county           190571 non-null object
n_killed                 190571 non-null int64
n_injured                190571 non-null int64
latitude                 190571 non-null float64
longitude                190571 non-null float64
participant_age_group    190571 non-null object
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 13.1+ MB


**Next, I want to do any needed subsetting of my data for easy visualization and analysis**

In [30]:
new_guns["month-year"]=pd.to_datetime(new_guns['date']).dt.to_period('M')
new_guns.head(2)

date         state city_or_county  n_killed  n_injured  latitude  \
0 2013-01-01  Pennsylvania     Mckeesport         0          4   40.3467   
1 2013-01-01    California      Hawthorne         1          3   33.9090   

   longitude                              participant_age_group month-year  
0   -79.8559  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...    2013-01  
1  -118.3330  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...    2013-01

In [31]:
new_guns.shape

(190571, 9)

At the end of cleaning the data, my new data contains 9 variables and 190571 observations.


**END OF DATA CLEANING**

Reference

Retrieved from [Source code](https://www.dataquest.io/blog/python-datetime-tutorial/)

Retrieved from [Source code](https://github.com/pandas-profiling/pandas-profiling)

cmdline(2018).Python and R Tips. Retrieved from [Source code](https://cmdlinetips.com/2018/04/how-to-drop-one-or-more-columns-in-pandas-dataframe/amp/)